"""Layer 4: Workflows providing public API entry points."""

from plotsmith.workflows.workflows import (
    figure,
    plot_backtest,
    plot_bar,
    plot_box,
    plot_correlation,
    plot_dumbbell,
    plot_forecast_comparison,
    plot_heatmap,
    plot_histogram,
    plot_lollipop,
    plot_metric,
    plot_model_comparison,
    plot_range,
    plot_residuals,
    plot_scatter,
    plot_slope,
    plot_timeseries,
    plot_violin,
    plot_waffle,
    plot_waterfall,
    small_multiples,
)

__all__ = [
    "figure",
    "plot_backtest",
    "plot_bar",
    "plot_box",
    "plot_correlation",
    "plot_dumbbell",
    "plot_forecast_comparison",
    "plot_heatmap",
    "plot_histogram",
    "plot_lollipop",
    "plot_metric",
    "plot_model_comparison",
    "plot_range",
    "plot_residuals",
    "plot_scatter",
    "plot_slope",
    "plot_timeseries",
    "plot_violin",
    "plot_waffle",
    "plot_waterfall",
    "small_multiples",
]
