"""PlotSmith: A layered plotting library for ML models."""

# Public API: Only workflows and view objects
from plotsmith.exceptions import PlotError, PlotSmithError, TaskError, ValidationError
from plotsmith.objects import (
    BandView,
    BarView,
    BoxView,
    DumbbellView,
    FigureSpec,
    HeatmapView,
    HistogramView,
    LollipopView,
    MetricView,
    RangeView,
    ScatterView,
    SeriesView,
    SlopeView,
    ViolinView,
    WaffleView,
    WaterfallView,
)
from plotsmith.primitives.draw import (
    ACCENT,
    accent_point,
    add_range_frame,
    direct_label,
    emphasize_last,
    event_line,
    force_bar_zero,
    minimal_axes,
    note,
    style_bar_plot,
    style_line_plot,
    style_scatter_plot,
    tidy_axes,
)
from plotsmith.workflows import (
    figure,
    plot_backtest,
    plot_bar,
    plot_box,
    plot_correlation,
    plot_dumbbell,
    plot_forecast_comparison,
    plot_heatmap,
    plot_histogram,
    plot_lollipop,
    plot_metric,
    plot_model_comparison,
    plot_range,
    plot_residuals,
    plot_scatter,
    plot_slope,
    plot_timeseries,
    plot_violin,
    plot_waffle,
    plot_waterfall,
    small_multiples,
)

__all__ = [
    # Exceptions
    "PlotSmithError",
    "ValidationError",
    "PlotError",
    "TaskError",
    # View objects
    "BandView",
    "BarView",
    "BoxView",
    "DumbbellView",
    "FigureSpec",
    "HeatmapView",
    "HistogramView",
    "LollipopView",
    "MetricView",
    "RangeView",
    "ScatterView",
    "SeriesView",
    "SlopeView",
    "ViolinView",
    "WaffleView",
    "WaterfallView",
    # Workflows
    "figure",
    "plot_backtest",
    "plot_bar",
    "plot_box",
    "plot_correlation",
    "plot_dumbbell",
    "plot_forecast_comparison",
    "plot_heatmap",
    "plot_histogram",
    "plot_lollipop",
    "plot_metric",
    "plot_model_comparison",
    "plot_range",
    "plot_residuals",
    "plot_scatter",
    "plot_slope",
    "plot_timeseries",
    "plot_violin",
    "plot_waffle",
    "plot_waterfall",
    "small_multiples",
    # Styling helpers
    "ACCENT",
    "accent_point",
    "add_range_frame",
    "direct_label",
    "emphasize_last",
    "event_line",
    "force_bar_zero",
    "minimal_axes",
    "note",
    "style_bar_plot",
    "style_line_plot",
    "style_scatter_plot",
    "tidy_axes",
]
